### ISSUE TITLE
Seems to be a problem with the link to refresh token

### ISSUE THREAD

**Issue by Will12123** [jborchma/qtrade#70] opened 2022-12-21 15:54 UTC
Maybe a url link needs to be updated in your functions. If I can update it myself I don't mind doing it, if you can tell me where it is in the code.¸

I simply coded:

from qtrade import Questrade                                    
qtrade = Questrade(access_code='abc')         #abc is my personnel token

The output is the error code:    

raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 500 Server Error: Internal Server Error for url: https://login.questrade.com/oauth2/token?grant_type=refresh_token&refresh_token=MyqKC7-5ywmcBAPmPzjJfzjgToQYM3P90

Your help would be apprciated

**Comment by jborchma** [comment] 2023-02-18 16:43
Sorry for the crazy late delay in response. I am not able to reproduce this error, connecting for me works just fine. So I am thinking this might be a problem on your side and not something wrong with the package.

**Comment by jborchma** [comment] 2023-02-25 18:49
Going to close this for now.

**Closed by jborchma** 2023-02-25 18:49 UTC
